// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsZtsueJqtFT-bqGjSFU5Q1UxV42bha0k',
    appId: '1:17012997528:web:c2b203664e0ca847647fed',
    messagingSenderId: '17012997528',
    projectId: 'qrcheck-f35ed',
    authDomain: 'qrcheck-f35ed.firebaseapp.com',
    storageBucket: 'qrcheck-f35ed.appspot.com',
    measurementId: 'G-HY1DHNGTN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7BliIqWYEkhZWY6I9jmarB6D2lKBr7ao',
    appId: '1:17012997528:android:47e1b704e3eec53f647fed',
    messagingSenderId: '17012997528',
    projectId: 'qrcheck-f35ed',
    storageBucket: 'qrcheck-f35ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtMhxqPoe1g3Jb9zxPw1J-a8swGpttsp0',
    appId: '1:17012997528:ios:0d2cfc3b83812c2c647fed',
    messagingSenderId: '17012997528',
    projectId: 'qrcheck-f35ed',
    storageBucket: 'qrcheck-f35ed.appspot.com',
    iosBundleId: 'com.example.qrcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtMhxqPoe1g3Jb9zxPw1J-a8swGpttsp0',
    appId: '1:17012997528:ios:7f311ef60d328dd3647fed',
    messagingSenderId: '17012997528',
    projectId: 'qrcheck-f35ed',
    storageBucket: 'qrcheck-f35ed.appspot.com',
    iosBundleId: 'com.example.qrcheck.RunnerTests',
  );
}
